kind: Pod
apiVersion: v1
metadata:
  name: isilon-provisioner
spec:
  containers:
    - name: isilon-provisioner
      image: hrynic/isilon_provisioner:latest
      imagePullPolicy: "IfNotPresent"
      env:
        - name: SERVER
          value: 192.168.5.200
        - name: PATH
          value: /ifs/test
        - name: USER
          value: admin
        - name: PASS
          value: password
        - name: GROUP
          value: Users
        - name: ISI_QUOTA_ENABLE
          value: "true"
